// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBfegv309uLrb3zw7XSGDjm3EB6U5x1xY',
    appId: '1:786908376704:web:33452ee149ceb909de0065',
    messagingSenderId: '786908376704',
    projectId: 'fb-app-distribution',
    authDomain: 'fb-app-distribution.firebaseapp.com',
    storageBucket: 'fb-app-distribution.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvTWarT9PwfNSceXXPDN0rhLvyE0O_cjM',
    appId: '1:786908376704:android:38c715dfe6f794f5de0065',
    messagingSenderId: '786908376704',
    projectId: 'fb-app-distribution',
    storageBucket: 'fb-app-distribution.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxsJUBsfUK3yujnA6z51Xse8nnwd_hHwM',
    appId: '1:786908376704:ios:f36c5621221b4556de0065',
    messagingSenderId: '786908376704',
    projectId: 'fb-app-distribution',
    storageBucket: 'fb-app-distribution.appspot.com',
    iosClientId: '786908376704-c52egrlu9jgig0669f82nbvtvb0in3if.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAppDistribution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxsJUBsfUK3yujnA6z51Xse8nnwd_hHwM',
    appId: '1:786908376704:ios:f36c5621221b4556de0065',
    messagingSenderId: '786908376704',
    projectId: 'fb-app-distribution',
    storageBucket: 'fb-app-distribution.appspot.com',
    iosClientId: '786908376704-c52egrlu9jgig0669f82nbvtvb0in3if.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAppDistribution',
  );
}
