name: App Distribution

on:
  push:
    branches: [master]
    paths-ignore:
      - "**/README.md"
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ubuntu-flutter

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 11.x

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.8.1

      - run: flutter pub get
      - run: flutter pub run build_runner build
      #- run: flutter format --set-exit-if-changed .
      - run: flutter analyze .
      - run: flutter test
      - run: flutter build apk

      # Upload generated apk to the artifacts
      - uses: actions/upload-artifact@master
        with:
          name: apk-release
          path: build/app/outputs/apk/release/app-release.apk

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APPID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: build/app/outputs/apk/release/app-release.apk

      # Build Web
      - run: flutter build web --release
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{secrets.GITHUB_TOKEN}}"
          firebaseServiceAccount: "${{secrets.FIREBASE_SERVICE_ACCOUNT_FB_APP_DISTRIBUTION}}"
        env: 
          FIREBASE_CLI_PREVIES: hostingchannels
